---
name: Build and deploy WAR app to Azure Web App - KiranAmazongit
on:
  push:
    branches:
      - master
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: microsoft
      - name: Build WAR with Maven (from subdirectory)
        run: mvn clean package
        working-directory: Amazon
      - name: List contents of target
        run: ls -R Amazon/Amazon-Web/target
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: Java-app
          path: Amazon/Amazon-Web/target/Amazon.war
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A0E04A2745F643E2A2BD723E47C6A7E0
            }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6DE274486BBA42889D40E7CC2C17E85E
            }}
          subscription-id: ${{
            secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5FD7F2FEDD7548CC80623EF7C2E0E27D
            }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: KiranAmazongit
          slot-name: Production
          package: "**/*.war"
