# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - KiranAmazongit

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'microsoft'

      - name: Build WAR with Maven (from subdirectory)
        run: mvn clean package
        working-directory: Amazon

      - name: List contents of target
        run: ls -R Amazon/Amazon-Web/target

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'Java-app' #same name to be used in upload and download
          path: Amazon/Amazon-Web/target/Amazon.war

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: 'Java-app' #same name to be used in upload and download

      - name: Deploy WAR to Azure Web App using Publish Profile
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'kiranamazongit-gybmhnheagbhhvav' #Exactly same as appservice name
          slot-name: 'kiranamazongit-dev'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: '**/Amazon.war'  # if war file insise some directroy then can use this.









