# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - KiranAmazongit

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'microsoft'

      - name: Build WAR with Maven (from subdirectory)
        run: mvn clean package
        working-directory: Amazon

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: Amazon/target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy WAR to Azure Web App using Publish Profile
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'KiranAmazongit'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: '*.war'

